[package]
name = "vello_example"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vello"
path = "vello.rs"

[dependencies]
tinyvg-rs = { path = "../.." }

peniko = "0.4.0"
winit = "0.30.10"
pollster = "0.4.0"
vello = {version = "0.5.0", default-features = false, features = ["wgpu"]}